$engine: 3
$onesync: legacy
name: NoPixelFiles
version: 3.3.0
author: some random dude
description: A 

tasks:

  - action: download_github
    src: https://github.com/swxy/NoPixelServer
    dest: ./







  
    
  
  
    
  
    
  
  
